RESULTS:: 16:52:10: root                                   pydial.py <train_command>816 :  List of domains: CamRestaurants
RESULTS:: 16:52:10: root                                      pydial.py <trainBatch>421 :  *** Training Iteration cur_env3-dqn-CR-seed4-15.0->cur_env3-dqn-CR-seed4-15.1: iter=0, error-rate=15, num-dialogs=1000 ***
ERROR  :: 16:52:29: root                              ContextLogger.py <_exceptHook>263 :  Uncaught exception: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>( Key Variable not found in checkpoint
	 [[Node: curiosity/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_curiosity/save/Const_0_0, curiosity/save/RestoreV2/tensor_names, curiosity/save/RestoreV2/shape_and_slices)]]

Caused by op u'curiosity/save/RestoreV2', defined at:
  File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dial/pw439/pydial/pydial.py", line 1174, in <module>
    run()
  File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 196, in autocmds
    add_verbosity_option=add_verbosity_option)
  File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 105, in parse_and_run_function
    return function(*args[:len(required_args)], **kw)
  File "/home/dial/pw439/pydial/pydial.py", line 817, in train_command
    trainBatch(domain, configId, gtrainerrorrate, gtraindialogsperbatch, i, seed=seed)
  File "/home/dial/pw439/pydial/pydial.py", line 459, in trainBatch
    simulator = Simulate.SimulationSystem(error_rate=error)
  File "/home/dial/pw439/pydial/Simulate.py", line 89, in __init__
    self.agent_factory = Agent.AgentFactory(hub_id='simulate')
  File "/home/dial/pw439/pydial/Agent.py", line 832, in __init__
    self.init_agents(hub_id)
  File "/home/dial/pw439/pydial/Agent.py", line 846, in init_agents
    self.agents['Smith'] = DialogueAgent(agent_id='Smith', hub_id=hub_id)  # primary agent, can be copied
  File "/home/dial/pw439/pydial/Agent.py", line 164, in __init__
    self.restart_agent(session_id=None)
  File "/home/dial/pw439/pydial/Agent.py", line 404, in restart_agent
    self._hand_control(domainString=self.topic_tracker.operatingDomain, previousDomainString=None)
  File "/home/dial/pw439/pydial/Agent.py", line 479, in _hand_control
    self._bootup(domainString, previousDomainString)
  File "/home/dial/pw439/pydial/Agent.py", line 509, in _bootup
    self.policy_manager.bootup(domainString)
  File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 92, in bootup
    self._load_domains_policy(domainString)
  File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 275, in _load_domains_policy
    self.domainPolicies[domainString] = DQNPolicy.DQNPolicy(in_policy_file, out_policy_file, domainString, learning)
  File "/home/dial/pw439/pydial/policy/DQNPolicy.py", line 403, in __init__
    self.h2_size, dropout_rate=self.dropout_rate)
  File "/home/dial/pw439/pydial/policy/DRL/dqn.py", line 97, in __init__
    self.predictor = mpc.StateActionPredictor(268, 16, designHead='pydial')  # todo len state len action
  File "/home/dial/pw439/pydial/model_prediction_curiosity.py", line 332, in __init__
    self.saver = tf.train.Saver()
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Variable not found in checkpoint
	 [[Node: curiosity/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_curiosity/save/Const_0_0, curiosity/save/RestoreV2/tensor_names, curiosity/save/RestoreV2/shape_and_slices)]]
 )
          Traceback (most recent call last):
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
              main()
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
              globals = debugger.run(setup['file'], None, None, is_module)
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
              pydev_imports.execfile(file, globals, locals)  # execute the script
            File "/home/dial/pw439/pydial/pydial.py", line 1174, in <module>
              run()
            File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 196, in autocmds
              add_verbosity_option=add_verbosity_option)
            File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 105, in parse_and_run_function
              return function(*args[:len(required_args)], **kw)
            File "/home/dial/pw439/pydial/pydial.py", line 817, in train_command
              trainBatch(domain, configId, gtrainerrorrate, gtraindialogsperbatch, i, seed=seed)
            File "/home/dial/pw439/pydial/pydial.py", line 459, in trainBatch
              simulator = Simulate.SimulationSystem(error_rate=error)
            File "/home/dial/pw439/pydial/Simulate.py", line 89, in __init__
              self.agent_factory = Agent.AgentFactory(hub_id='simulate')
            File "/home/dial/pw439/pydial/Agent.py", line 832, in __init__
              self.init_agents(hub_id)
            File "/home/dial/pw439/pydial/Agent.py", line 846, in init_agents
              self.agents['Smith'] = DialogueAgent(agent_id='Smith', hub_id=hub_id)  # primary agent, can be copied
            File "/home/dial/pw439/pydial/Agent.py", line 164, in __init__
              self.restart_agent(session_id=None)
            File "/home/dial/pw439/pydial/Agent.py", line 404, in restart_agent
              self._hand_control(domainString=self.topic_tracker.operatingDomain, previousDomainString=None)
            File "/home/dial/pw439/pydial/Agent.py", line 479, in _hand_control
              self._bootup(domainString, previousDomainString)
            File "/home/dial/pw439/pydial/Agent.py", line 509, in _bootup
              self.policy_manager.bootup(domainString)
            File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 92, in bootup
              self._load_domains_policy(domainString)
            File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 275, in _load_domains_policy
              self.domainPolicies[domainString] = DQNPolicy.DQNPolicy(in_policy_file, out_policy_file, domainString, learning)
            File "/home/dial/pw439/pydial/policy/DQNPolicy.py", line 403, in __init__
              self.h2_size, dropout_rate=self.dropout_rate)
            File "/home/dial/pw439/pydial/policy/DRL/dqn.py", line 97, in __init__
              self.predictor = mpc.StateActionPredictor(268, 16, designHead='pydial')  # todo len state len action
            File "/home/dial/pw439/pydial/model_prediction_curiosity.py", line 336, in __init__
              self.saver.restore(self.sess, '_curiosity_model/pretrg_model/trained_curiosity100') #TODO
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
              {self.saver_def.filename_tensor_name: save_path})
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
              run_metadata_ptr)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
              feed_dict_tensor, options, run_metadata)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
              run_metadata)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
              raise type(e)(node_def, op, message)
          NotFoundError: Key Variable not found in checkpoint
          	 [[Node: curiosity/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_curiosity/save/Const_0_0, curiosity/save/RestoreV2/tensor_names, curiosity/save/RestoreV2/shape_and_slices)]]
          
          Caused by op u'curiosity/save/RestoreV2', defined at:
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
              main()
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
              globals = debugger.run(setup['file'], None, None, is_module)
            File "/opt/pycharm-community-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
              pydev_imports.execfile(file, globals, locals)  # execute the script
            File "/home/dial/pw439/pydial/pydial.py", line 1174, in <module>
              run()
            File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 196, in autocmds
              add_verbosity_option=add_verbosity_option)
            File "/home/dial/pw439/.local/lib/python2.7/site-packages/scriptine/command.py", line 105, in parse_and_run_function
              return function(*args[:len(required_args)], **kw)
            File "/home/dial/pw439/pydial/pydial.py", line 817, in train_command
              trainBatch(domain, configId, gtrainerrorrate, gtraindialogsperbatch, i, seed=seed)
            File "/home/dial/pw439/pydial/pydial.py", line 459, in trainBatch
              simulator = Simulate.SimulationSystem(error_rate=error)
            File "/home/dial/pw439/pydial/Simulate.py", line 89, in __init__
              self.agent_factory = Agent.AgentFactory(hub_id='simulate')
            File "/home/dial/pw439/pydial/Agent.py", line 832, in __init__
              self.init_agents(hub_id)
            File "/home/dial/pw439/pydial/Agent.py", line 846, in init_agents
              self.agents['Smith'] = DialogueAgent(agent_id='Smith', hub_id=hub_id)  # primary agent, can be copied
            File "/home/dial/pw439/pydial/Agent.py", line 164, in __init__
              self.restart_agent(session_id=None)
            File "/home/dial/pw439/pydial/Agent.py", line 404, in restart_agent
              self._hand_control(domainString=self.topic_tracker.operatingDomain, previousDomainString=None)
            File "/home/dial/pw439/pydial/Agent.py", line 479, in _hand_control
              self._bootup(domainString, previousDomainString)
            File "/home/dial/pw439/pydial/Agent.py", line 509, in _bootup
              self.policy_manager.bootup(domainString)
            File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 92, in bootup
              self._load_domains_policy(domainString)
            File "/home/dial/pw439/pydial/policy/PolicyManager.py", line 275, in _load_domains_policy
              self.domainPolicies[domainString] = DQNPolicy.DQNPolicy(in_policy_file, out_policy_file, domainString, learning)
            File "/home/dial/pw439/pydial/policy/DQNPolicy.py", line 403, in __init__
              self.h2_size, dropout_rate=self.dropout_rate)
            File "/home/dial/pw439/pydial/policy/DRL/dqn.py", line 97, in __init__
              self.predictor = mpc.StateActionPredictor(268, 16, designHead='pydial')  # todo len state len action
            File "/home/dial/pw439/pydial/model_prediction_curiosity.py", line 332, in __init__
              self.saver = tf.train.Saver()
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
              self.build()
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
              self._build(self._filename, build_save=True, build_restore=True)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
              build_save=build_save, build_restore=build_restore)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
              restore_sequentially, reshape)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
              restore_sequentially)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
              return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
              shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
              op_def=op_def)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
              op_def=op_def)
            File "/home/dial/pw439/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
              self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
          
          NotFoundError (see above for traceback): Key Variable not found in checkpoint
          	 [[Node: curiosity/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_curiosity/save/Const_0_0, curiosity/save/RestoreV2/tensor_names, curiosity/save/RestoreV2/shape_and_slices)]]
          
          
