RESULTS:: 13:41:03: root                                   pydial.py <train_command>813 :  List of domains: CamRestaurants
RESULTS:: 13:41:03: root                                      pydial.py <trainBatch>420 :  *** Training Iteration testing-env1-dqn-CR-seed3-00.0->testing-env1-dqn-CR-seed3-00.1: iter=0, error-rate=0, num-dialogs=1000 ***
ERROR  :: 13:41:05: root                              ContextLogger.py <_exceptHook>263 :  Uncaught exception: <type 'exceptions.AttributeError'>( 'NoneType' object has no attribute 'run' )
          Traceback (most recent call last):
            File "pydial.py", line 1171, in <module>
              run()
            File "/usr/local/lib/python2.7/dist-packages/scriptine/command.py", line 196, in autocmds
              add_verbosity_option=add_verbosity_option)
            File "/usr/local/lib/python2.7/dist-packages/scriptine/command.py", line 105, in parse_and_run_function
              return function(*args[:len(required_args)], **kw)
            File "pydial.py", line 814, in train_command
              trainBatch(domain, configId, gtrainerrorrate, gtraindialogsperbatch, i, seed=seed)
            File "pydial.py", line 459, in trainBatch
              simulator.run_dialogs(ndialogs)
            File "/home/dial/pw439/pydial/Simulate.py", line 128, in run_dialogs
              self.run(session_id='simulate_dialog'+str(i), sim_level=self.sim_level)
            File "/home/dial/pw439/pydial/Simulate.py", line 204, in run
              domainSimulatedUsers=self.simulator.simUserManagers)
            File "/home/dial/pw439/pydial/Agent.py", line 339, in continue_call
              bonus = predictor.pred_bonus(prev_state_vec, state_vec, ac_1hot) # input: last_state, state, action
            File "/home/dial/pw439/pydial/model_prediction_curiosity.py", line 420, in pred_bonus
              error = sess.run(bonus, {self.s1: [s1], self.s2: [s2], self.asample: [asample]})
          AttributeError: 'NoneType' object has no attribute 'run'
          
